sudo: false
language: ruby
bundler_args: "--no-deployment"

before_script:
- puppet --version

script:
- bundle exec rake validate
- bundle exec rake lint
- bundle exec rake spec

matrix:
  fast_finish: true
  include:
  - rvm: 2.5
    env: PUPPET_VERSION="~> 5" DEPLOY="yes"
  - rvm: 2.4
    env: PUPPET_VERSION="~> 5.4"
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 4.6"
  - rvm: 2.2.5
    env: PUPPET_VERSION="~> 4.3"
  - rvm: 2.1.10
    env: PUPPET_VERSION="~> 4.2"

before_deploy:
- bundle exec puppet module build

deploy:
  provider: releases
  api-key:
      secure: c1nsisXrYLskSU2bm8n4t3m6rS5dr9W/xy2TVaRTPMwGTMJQZT3qwjLHXtxIu3OLqpZRTZJ68H9XXt5NQe7QjyGUqgpaVE2TaSAl0+qVa9lwlhWkQ9FESN6ZPbBIeh4zAtgRSpayNNzwnEzmEJGx+PVQJWqFlDOblKCbHSao6ec=
  file: "$(ls $TRAVIS_BUILD_DIR/pkg/s12v-blackfire-*.tar.gz | head -n 1)"
  skip_cleanup: true
  on:
    repo: s12v/puppet-blackfire
    tags: true
    all_branches: true
    condition: $DEPLOY = yes
